version: '3.5'

services:
  nginx:
    container_name: nginx
    build:
      context: ./etc/docker/nginx
    ports:
      - 300:80
    volumes:
      - ./public:/app/www/public
    depends_on:
      - php-fpm

  php-fpm:
    container_name: php-fpm
    build:
      context: ./etc/docker/php
    volumes:
      - ./:/app/www